### ISSUE TITLE
Add some helper functions or functionality

### ISSUE THREAD

**Issue by connelldave** [connelldave/botocove#16]
Having commonly wrapped functions importable, as well as more tricky ones, might be useful.

Some ideas:
- A check-func that just tries to assume roles in accounts given func args
- A multi-region helper that runs a Cove func in every region? Depends if a Boto session can inherit a regional default?

**Comment by iainelder** [comment]
Just noticed this. +1 for the multi-region support! I was going to suggest this after resolving my PR.

It's something I want to include in [aws-org-inventory](https://github.com/iainelder/aws-org-inventory).

When I need to collect inventory from multiple regions, I use this quick and dirty scripting like this:

```bash
export AWS_PROFILE=OrgMgmtRole

export AWS_DEFAULT_REGION=eu-west-1
aws-org-inventory config describe_configuration_recorders ConfigurationRecorders \
> configuration_recorders_eu-west-1.csv

export AWS_DEFAULT_REGION=eu-central-1
aws-org-inventory config describe_configuration_recorders ConfigurationRecorders \
> configuration_recorders_eu-central-1.csv

# And so on for each region ...
```

And so later I have to use something like [csvstack](https://csvkit.readthedocs.io/en/latest/scripts/csvstack.html) to unify the results.

**Comment by iainelder** [comment]
Earlier this year I put together an experimental multiregion boto client.

https://github.com/iainelder/aws-boto-multiregion-client

See the test_botocove.py script for an example of how it can be combined with botocove to get results from all regions in all accounts.

I was planning to (one day) use this client in aws-org-inventory, If it's something you think would make sense to include in botocove, feel free to adapt it.

**Comment by connelldave** [comment]
Regions are done - alternative formatter might be a nice idea

**Comment by iainelder** [comment]
> alternative formatter might be a nice idea

Do you mean instead of the default CoveOutput?

I've been experimenting with various post-processing techniques of CoveOutput for enrichment, steaming, or structured reporting.

If that's what you were referring to I could make some specific issues with suggestions and prototype solutions.

**Comment by connelldave** [comment]
I'm pretty happy to call Cove a library that can enable cool things as well as working standalone - closing this one as it doesn't really have any content in it now :)
