### ISSUE TITLE
Can we do without DescribeAccount?

### ISSUE THREAD

**Issue by iainelder** [connelldave/botocove#35]
[CoveSession](https://github.com/connelldave/botocove/blob/c0e8ff0c4bb9ba25057d7dd24c976b15d16251c7/botocove/cove_session.py#L41) calls [`DescribeAccount`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeAccount.html) once for each member account in the organization.

But [CoveHostAccount](https://github.com/connelldave/botocove/blob/c0e8ff0c4bb9ba25057d7dd24c976b15d16251c7/botocove/cove_host_account.py#L230) also calls [`ListAccount`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html) and pages it out fully, although everything except the account ID gets discarded.

DescribeAccount and ListAccount return the same attributes for each account.

I'm wondering if it would be possible to retain the list of `AccountTypeDef` instead of just a set of IDs so that `CoveSessionInformation` objects can be built without calling DescribeAccount.

The practical reason for doing that would be to avoid DescribeAccount's throttling errors (see #12 and #17). They happen less now, but you can still get them if you give `cove` a function that returns quickly enough.

Once, to avoid errors in downstream tooling, I needed to filter my organization's account list to only those that have a working OrganizationAccountAccessRole. Cove does that almost for free :-) But because my function was almost a no-op, the DescribeAccount API would sometimes fail.

**Comment by iainelder** [comment]
I'll work on this before any of the other issues.

My team reported some errors from botocove because of DescribeAccount throttling.

I suspect this is more likely to happen when there are instances of botocove running in parallel.

The DescribeAccounts API throttling limits are not published, but such limits are often per-account rather than per session. So more sessions running botocove would make it more likely to get a throttling error.

(I've opened an issue in the Organizations documentation to publish the throttling limits: https://github.com/awsdocs/aws-organizations-docs/issues/39)

**Comment by connelldave** [comment]
Interesting - good to know. Without looking at the codebase - can we tie this to the org master flag and just create a dict of `{id: AccountTypeDef}` after we do list accounts, and use that bool again to decide whether to check that dict for enrichment data?

**Comment by iainelder** [comment]
A dict of account IDs to AccountTypeDef is exactly what I was thinking as a new internal data structure. In that way you get the list of account IDs by iterating the keys and you get the enriched version by doing a key lookup.

I need to study the code to understand the org_master flag and to understand how this would work when we don't/can't  use ListAccounts to retrieve accounts.

**Comment by iainelder** [comment]
I believe this is now covered by #43 , released as version 1.6.2.

If you want to close it now, that's fine by me.

I'd also like to do a performance comparison of 1.6.1 and 1.6.2 to show whether there is a speedup. I could share that no-op code in the opening comment as a stress test and measure the the time taken to execute over X accounts.
