### ISSUE TITLE
Bump moto to 4.x

### ISSUE THREAD

**Issue by connelldave** [connelldave/botocove#54]
Upgrading moto to 4.x broke the test suite intermittently, and seemingly only in CI or on first run from a fresh container.

I lost far too much time working out what was even happening to persist any further, so moto is now pinned to a 3.x version that worked.

One day we should bump to the new moto release, but maybe after giving it a few months.

**Comment by iainelder** [comment]
Moto 4 advertises multi-account support.

That would be a compelling reason to upgrade if we can find a use for it in the test suite.

Otherwise, I'd stay on version 3 until they stop supporting it.

**Comment by iainelder** [comment]
From the releases, it looks like version 3 is no longer being maintained.

The latest release of version 3 is [3.1.18](https://github.com/getmoto/moto/releases/tag/3.1.18) on 2022-08-12.

The latest release of version 4 is [4.16](https://github.com/getmoto/moto/releases/tag/4.1.6) on 2023-03-26.

I'll see how the tests run with the latest version and make a PR for this if it works.
