### ISSUE TITLE
Continue to support Python 3.8

### ISSUE THREAD

**Issue by iainelder** [connelldave/botocove#56]
I see that the minimum Python version supported by botocove is now 3.9.

https://github.com/connelldave/botocove/blob/2998813048a55d5dc793981f4509c295e7eea8db/pyproject.toml#L12

This breaks botocove for me.

I've been using Python 3.8 for everything right now because that's what ships with Ubuntu 20.

Why has the minimum version been increased to Python 3.9?

If it has to be that way, how do I set up Python 3.9 in my projects?

I get an errors like the below now when developing botocove.

```console
$ poetry run pre-commit run --all-files

Current Python version (3.8.10) is not allowed by the project (^3.9).
Please change python executable via the "env use" command.
$ poetry env use 3.9
pyenv: python3.9: command not found

The `python3.9' command exists in these Python versions:
  3.9.9

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Command python3.9 -c "import sys; print(sys.executable)" errored with the following return code 127, and output: 

```

As a workaround for now I'll pin my other projects that use botocove to version 1.7.0.

**Comment by connelldave** [comment]
oh, whoops - I didn't intend to ship that, I was just trying to work out what on earth had changed for tests to fail specifically in github actions and not an ubuntu VM, and do so in a non-deterministic way (different failures for different runs in gh actions). I'll revert this evening.

**Comment by iainelder** [comment]
Thanks! No worries.

Are these the same failures you referred to in #54?

**Comment by connelldave** [comment]
Yes - I tried a bunch of things and couldn't repro without a fresh container, and I ran out of patience before I managed to even consistently do that.

https://github.com/connelldave/botocove/releases/tag/v1.7.1 addresses this issue :)

**Comment by iainelder** [comment]
Working fine again for me. Thanks!
