### ISSUE TITLE
Support alternative AWS Paritions (e.g. GovCloud `aws-us-gov`)

### ISSUE THREAD

**Issue by ryno75** [connelldave/botocove#63]
The current version of botocove is unable to run against any non-default (i.e. `aws`) AWS Paritions.
This means that neither AWS GovCloud or China Partitions/Regions are supported.

Recommending adding a cove decorator argument to allow for an override with a default value derived from the default session (i.e. host account) called identity.

For further detail on AWS Partitions see: https://docs.amazonaws.cn/en_us/general/latest/gr/aws-arns-and-namespaces.html

**Comment by iainelder** [comment]
I guess you are the first botocove user to work outside the `aws` partition :-)

Seems like a good thing to support. I've left more feedback on your PR. Thanks!

**Comment by iainelder** [comment]
[Botocove version 1.7.3](https://github.com/connelldave/botocove/releases/tag/v1.7.3) supports different AWS partitions.

I'll close this now.

Thanks @ryno75 for your contribution.

If you have any feedback about the new feature, feel free to comment here or in a new issue.
