### ISSUE TITLE
Is botocove compatible with Python 3.11, 3.12?

### ISSUE THREAD

**Issue by iainelder** [connelldave/botocove#81]
[Sceptre](https://github.com/Sceptre/sceptre) wears a badge in its README to show its Python feature version compatibility.

```markdown
[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/sceptre?logo=pypi)](https://pypi.org/project/sceptre/?logo=pypi)
```

The badge today shows correctly that Sceptre supports Python feature versions 3.7, 3.8, 3.9, 3.10, and 3.11.

![image](https://github.com/connelldave/botocove/assets/5024311/9f4040f6-a8c8-459c-ad6e-60316e38452a)

A site called shields.io [hosts the API to generate the badge](https://shields.io/badges/py-pi-python-version). I used it to generate a badge for botocove.

```markdown
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/botocove)
```

The result surprised me. The badge shows that botocove is compatible with Python feature versions 3.8, 3.9, and 3.10.

![image](https://github.com/connelldave/botocove/assets/5024311/0c66fea3-bf88-4e1f-9e53-024977ef0699)

What about 3.11 and 3.12?

I don't see anything obvious in pyproject.toml that would block these versions, but there may be a dependency that causes it. (My guess is [something unmaintained such as flakeheaven is dragging us down](https://github.com/connelldave/botocove/pull/78).)

**Comment by connelldave** [comment]
I think this might just be that poetry is pinned to 1.2 and 3.11 came out after 1.2 - I'll have a look at bumping to latest. I don't love this is pinned in the actions yaml, but also I don't love the idea of pulling a $latest of a build tool either...

**Comment by connelldave** [comment]
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/botocove?cacheSeconds=0)

:)

**Comment by connelldave** [comment]
> Since it's just one component to bootstrap Poetry, I think it's fine. Where else would you put it?

I considered requirements-dev.txt to define the version when pip installing poetry to start the chain, maybe use `pipx` instead, but that's only really useful if relying on dependabot or something (since the dependency is defined somewhere tool-aware).

**Comment by connelldave** [comment]
> PRs [82](https://github.com/connelldave/botocove/pull/82) and [83](https://github.com/connelldave/botocove/pull/83) add support for Python 3.11 and 3.12.

As previous comment, thats not strictly true :)

**Comment by iainelder** [comment]
[Thanks for explaining in this comment](https://github.com/connelldave/botocove/pull/82#discussion_r1405460001).

PyPI's metadata about the Python versions was incorrect, and shields.io reads that metadata to generate the badge.

Using Python 3.11 and Python 3.12 the package was always pip-installable.
