### ISSUE TITLE
Allow custom RoleSessionName

### ISSUE THREAD

**Issue by SantiRaposo** [connelldave/botocove#9]
Hello,

It would be quite useful for me if I was able to pass a custom `RoleSessionName` to the cove decorator instead of using the default (which is the `rolename` variable). My organization has defined some conditions on assuming roles and using the `RoleName` as the `RoleSessionName` does not satisfy these conditions.

I took a look at the code and it seems that this could be a minor change, I could make a small PR with the changes to the code and documentation if you feel like this would be welcome.

**Comment by connelldave** [comment]
Hello - sounds like a helpful improvement! Feel free to raise a PR :)

**Comment by connelldave** [comment]
This is released on https://pypi.org/project/botocove/ as 1.3.0 :)
